image: archlinux
sources:
  - "https://github.com/49e94b8f256530dc0d41f740dfe8a4c1/blog"
secrets:
  - b03d783e-d793-479d-8558-082abb0ab74a
  - 7619d574-cfe1-4a08-9a1d-df3a5499c31e
packages:
  - ruby
  - nodejs-lts-fermium
tasks:
  - setup: |
      if [ "$(git rev-parse origin/develop)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
      ruby -v
      gem -v
      export PATH=$(ruby -e 'puts Gem.user_dir')/bin:$PATH
      gem install --user-install bundler
      cd blog
      sudo chown -R $(whoami) ~/.gem/*
      bundle install
  - build: |
      cd blog
      JEKYLL_ENV=production
      export PATH=$(ruby -e 'puts Gem.user_dir')/bin:$PATH
      bundle exec jekyll build
  - deploy: |
      cd blog
      DEPLOY_HOST=168.119.234.216
      DEPLOY_USER=ken
      eval `ssh-agent`
      ssh-add ~/.ssh/b03d783e-d793-479d-8558-082abb0ab74a
      ln -s ~/.ssh/7619d574-cfe1-4a08-9a1d-df3a5499c31e ~/.ssh/id_rsa.pub
      scp -o StrictHostKeyChecking=no -rv _site/* $DEPLOY_USER@$DEPLOY_HOST:/var/www/html/blog
