title: Ken's Blog
author: Ken Okech
description: This is Ken's blog.

url: "https://blog.psr42.com"
baseUrl: "/"

theme: minima

minima:
  skin: dark

sass:
  style: compressed
  sass_dir: scss

plugins:
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-toc
exclude:
  - .build.yml
  - docker-compose.*
  - scss
