title: Ken's Blog
author: Ken Okech
subtitle: This is Ken's blog.

url: "https://blog.psr42.com"
baseUrl: "/"

footer_only_homepage: false
footer_url: "https://github.com/49e94b8f256530dc0d41f740dfe8a4c1"
footer_text: "Ken's Awesome Blog"

profile-picture: assets/profile.png

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    link: "about"
  - name: "Resume"
    absolute-link: "https://pro-panda.github.io/resume.pdf"

plugins:
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-minifier

exclude:
  - docker-compose.*
  - .build.yml
